create table tasks (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
description VARCHAR(50) NOT NULL,
status ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED') NOT NULL,
local_date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);